name: image_size_getter_http_input
description: A http input for image_size_getter.
version: 1.0.0
homepage: https://github.com/CaiJingLong/dart_image_size_getter/tree/master/image_size_getter_http_input

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  # image_size_getter: ^1.1.0
  http: ^0.13.4
  # image_size_getter:
  #   path: ../library
  image_size_getter: ^1.1.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
